FGW-Enterprise-Web.AddminApp/Controllers/Components/PagerViewComponent.cs
using FGW_Enterprise_Web.ViewModels.Common;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FGW_Enterprise_Web.AddminApp.Controllers.Components
{
    public class PagerViewComponent: ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PageResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Defaults", result));
        }
    }
}

FGW-Enterprise-Web.AddminApp/Controllers/LoginController.cs
using FGW_Enterprise_Web.AddminApp.Service;
using FGW_Enterprise_Web.ViewModels.System.Users;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Logging;
using Microsoft.IdentityModel.Tokens;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace FGW_Enterprise_Web.AddminApp.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUserApiClient _userApiClient;
        private readonly IConfiguration _configuration;

        public LoginController(IUserApiClient userApiClient,
            IConfiguration configuration)
        {
            _userApiClient = userApiClient;
            _configuration = configuration;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginRequest request)
        {
            if (!ModelState.IsValid)
                return View(ModelState);
            var result = await _userApiClient.Authenticate(request);
            if (result.ResultObj == null)
            {
                ModelState.AddModelError("",result.Message);
                return View();
            }
            //View(token);
            var userPrincipal = this.ValidateToken(result.ResultObj);
            var authProperties = new AuthenticationProperties
            {
                ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10),
                IsPersistent = false
            };
            HttpContext.Session.SetString("Token", result.ResultObj);

            await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        userPrincipal,
                        authProperties);

            return RedirectToAction("Index", "Home");
        }
        private ClaimsPrincipal ValidateToken(string jwtToken)
        {
            IdentityModelEventSource.ShowPII = true;

            SecurityToken validatedToken;
            TokenValidationParameters validationParameters = new TokenValidationParameters();

            validationParameters.ValidateLifetime = true;
            validationParameters.ValidAudience = _configuration["Tokens:Issuer"];
            validationParameters.ValidIssuer = _configuration["Tokens:Issuer"];
            validationParameters.IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_configuration["Tokens:Key"]));
            ClaimsPrincipal principal = new JwtSecurityTokenHandler().ValidateToken(jwtToken, validationParameters, out validatedToken);
            //    View(principal);
            return principal;

        }
    }
}

FGW-Enterprise-Web.AddminApp/Controllers/UserController.cs
using FGW_Enterprise_Web.AddminApp.Service;
using FGW_Enterprise_Web.ViewModels.Catalog.Email;
using FGW_Enterprise_Web.ViewModels.Common;
using FGW_Enterprise_Web.ViewModels.System.Users;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Logging;
using Microsoft.IdentityModel.Tokens;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace FGW_Enterprise_Web.AddminApp.Controllers
{
    public class UserController : BaseController
    {
        private readonly IUserApiClient _userApiClient;
        private readonly IConfiguration _configuration;
        private readonly IRoleApiClient _roleApiClient;

        public UserController(IUserApiClient userApiClient,
           IRoleApiClient roleApiClient,
           IConfiguration configuration)
        {
            _roleApiClient = roleApiClient;
            _userApiClient = userApiClient;
            _configuration = configuration;
        }
        public async Task<IActionResult> Index(string keyword, int pageIndex = 1, int pageSize = 10)
        {
            var request = new GetUserPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _userApiClient.GetUserPagings(request);
            ViewBag.Keyword = keyword;
            if (TempData["result"] != null)
            {
                ViewBag.SuccessMessage = TempData["result"];
            }
            return View(data.ResultObj);
        }



        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var result = await _userApiClient.GetById(id);
            return View(result.ResultObj);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(RegisterRequest request)
        {
            if (!ModelState.IsValid)
                return View();
            var result = await _userApiClient.RegisterUser(request);
            if (result.ISuccessed)
            {
                TempData["result"] = "Create successfully";
                return RedirectToAction("Index");

            }
            ModelState.AddModelError("", result.Message);
            return View(request);
        }



        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var result = await _userApiClient.GetById(id);
            if (result.ISuccessed)
            {
                var user = result.ResultObj;
                var updateRequest = new UserUpdateRequest()
                {
                    Dob = user.DoB,
                    Email = user.Email,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    FullName = user.FullName,
                    Id = id
                };
                return View(updateRequest);

            }
            return RedirectToAction("Error", "Home");

        }
        [HttpPost]
        public async Task<IActionResult> Edit(UserUpdateRequest request)
        {
            if (!ModelState.IsValid)
                return View();
            var result = await _userApiClient.EditUser(request.Id, request);
            if (result.ISuccessed)
            {
                TempData["result"] = "Edit successfully";
                return RedirectToAction("Index");

            }
            ModelState.AddModelError("", result.Message);
            return View(request);
        }


        [HttpPost]
        public async Task<IActionResult> Logout()
        {

            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Remove("Token");
            return RedirectToAction("Index", "Login");

        }

        //
        [HttpGet]
        public IActionResult Delete(Guid id)
        {
            return View(new DeleteUserRequest()
            {
                Id = id
            }); ;
        }


        [HttpPost]
        public async Task<IActionResult> Delete(DeleteUserRequest deleteRequest)
        {
            if (!ModelState.IsValid)
                return View();
            var result = await _userApiClient.Delete(deleteRequest.Id);
            if (result.ISuccessed)
            {
                TempData["result"] = "Delete successfully";
                return RedirectToAction("Index");

            }
            ModelState.AddModelError("", result.Message);
            return View(deleteRequest);
        }


        [HttpGet]
        public async Task<IActionResult> RoleAssign(Guid id)
        {
            var roleAssignRequest = await GetRoleAssignRequest(id);
            return View(roleAssignRequest);
        }

        [HttpPost]
        public async Task<IActionResult> RoleAssign(RoleAssignRequest request)
        {
            if (!ModelState.IsValid)
                return View();
            var result = await _userApiClient.RoleAssign(request.Id, request);
            if (result.ISuccessed)
            {
                TempData["result"] = "Success to Assign User";
                return RedirectToAction("Index");

            }

            ModelState.AddModelError("", result.Message);
            var roleAssignRequest = await GetRoleAssignRequest(request.Id);
            return View(roleAssignRequest);
        }
        private async Task<RoleAssignRequest> GetRoleAssignRequest(Guid id)
        {
            var userObj = await _userApiClient.GetById(id);
            var rolesObj = await _roleApiClient.GetAll();
            var roleAssignRequest = new RoleAssignRequest();
            foreach (var role in rolesObj.ResultObj)
            {
                roleAssignRequest.Roles.Add(new SelectedItems()
                {
                    Id = role.Id.ToString(),
                    Name = role.Name,
                    Selected = userObj.ResultObj.Roles.Contains(role.Name)
                });
            }
            return roleAssignRequest;
        }
        [HttpGet]
        public IActionResult GetMail()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> GetMail(GetEmailRequest request)
        {


            String reciever = request._mailnhan;
            String sender = request._mailgui;
            String title = request._chude;
            String body = request._noidung;

            string account = request._smtpacount;
            string pass = request._smtppassword;


            var result = await _userApiClient.SendMailGoogleSmtp(sender, reciever, title, body, account, pass);

            return Ok(result);
        }


    }
}

FGW-Enterprise-Web.AddminApp/Views/User/Create.cshtml
@model FGW_Enterprise_Web.ViewModels.System.Users.RegisterRequest

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<h4>RegisterRequest</h4>


<div class="container-fluid">

    <h1 class="mt-4">Create new</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home Page</a></li>
        <li class="breadcrumb-item active">Create new User</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="User">Back to list</a>
        </div>

        <div class="card-body">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="user_FirstName" class="control-label"></label>
                        <input asp-for="user_FirstName" class="form-control" />
                        <span asp-validation-for="user_FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="user_LastName" class="control-label"></label>
                        <input asp-for="user_LastName" class="form-control" />
                        <span asp-validation-for="user_LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="user_FullName" class="control-label"></label>
                        <input asp-for="user_FullName" class="form-control" />
                        <span asp-validation-for="user_FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="user_DOB" class="control-label"></label>
                        <input asp-for="user_DOB" class="form-control" />
                        <span asp-validation-for="user_DOB" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="UserName" class="control-label"></label>
                        <input asp-for="UserName" class="form-control" />
                        <span asp-validation-for="UserName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ConfirmPassword" class="control-label"></label>
                        <input asp-for="ConfirmPassword" class="form-control" />
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
    

FGW-Enterprise-Web.AddminApp/Views/User/Delete.cshtml
@model FGW_Enterprise_Web.ViewModels.System.Users.DeleteUserRequest

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="mt-4">Delete</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home Page</a></li>
    <li class="breadcrumb-item active">Delete User</li>
</ol>
<div class="card mb-4">
    <div class="card-header">
        <a class="btn btn-success" asp-action="Index" asp-controller="User">Back to list</a>
    </div>
    <div class="card-body">
        <div class="col-md-12">
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Id)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Id)
                </dd>
            </dl>

            <form asp-action="Delete">
                <input asp-for="Id" type="hidden" />
                <input type="submit" value="Delete" class="btn btn-danger" /> |
            </form>
        </div>
    </div>
</div>

FGW-Enterprise-Web.AddminApp/Views/User/Details.cshtml
@model FGW_Enterprise_Web.ViewModels.System.Users.UserVm

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h1 class="mt-4">Create new</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home Page</a></li>
        <li class="breadcrumb-item active">Detail User</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="User">Back to list</a>
        </div>
        <div class="card-body">
            <div class="col-md-12">
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.FullName)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.FullName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.FirstName)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.FirstName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.LastName)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.LastName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.DoB)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.DoB)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Email)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Email)
                    </dd>
                </dl>
            </div>
        </div>
    </div>
</div>

FGW-Enterprise-Web.AddminApp/Views/User/Edit.cshtml
@model FGW_Enterprise_Web.ViewModels.System.Users.UserUpdateRequest

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>Create</h1>

<h4>RegisterRequest</h4>


<div class="container-fluid">
    <h1 class="mt-4">Edit</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home Page</a></li>
        <li class="breadcrumb-item active">Edit User</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="User">Back to list</a>
        </div>

        <div class="card-body">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="FirstName" class="control-label"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Dob" class="control-label"></label>
                        <input asp-for="Dob" class="form-control" />
                        <span asp-validation-for="Dob" class="text-danger"></span>
                    </div>
                   
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                   
                    
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

FGW-Enterprise-Web.AddminApp/Views/User/Index.cshtml
@using FGW_Enterprise_Web.ViewModels.Common;
@model PagedResult<FGW_Enterprise_Web.ViewModels.System.Users.UserVm>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{ 
    <script>
        setTimeout(function () {
            $('#alertMessage').fadeOut('slow');
        }, 2000);
    </script>
}

<div class="container-fluid">
    <h1 class="mt-4">List of User</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="index.html">Home Page</a></li>
        <li class="breadcrumb-item active">List of User</li>
    </ol>
  
    <div class="card mb-12">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6 col-xs-12">
                    <a class="btn btn-success" asp-action="Create" asp-controller="User">Create New</a>
                </div>
                <div class="col-md-6 col-xs-12">
                    <a class="btn btn-success" asp-action="GetMail" asp-controller="User">Send</a>
                </div>
                <div class="col-md-6 col-xs-12">
                    <form asp-action="Index" method="get">
                        <div class="row">
                            <div class="col-md-9">
                                <input type="text" value="@ViewBag.Keyword" name="keyword" class="form-control" />
                            </div>
                            <div class="col-md-3">
                                <button type="submit" class="btn btn-primary">Find</button>
                                <button type="reset" onclick="window.location.href='/User/Index'" class="btn btn-dark">Reset</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            </div>
            
    
    <div class="card-body">
       
        <div class="row">
            @if (ViewBag.SuccessMessage != null)
            {
                <div id="alertMessage" class="alert alert-dark" role="alert">
                    @ViewBag.SuccessMessage
                </div>
            }
        </div>
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>
                            Id
                        </th>
                        <th>
                            User Name
                        </th>
                        <th>
                            First Name
                        </th>
                        <th>
                            Last Name
                        </th>
                        <th>
                            Date of birth
                        </th>
                        <th>
                            Email
                        </th>
                        <th>
                            Role
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Items)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UserName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FirstName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LastName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DoB)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                      
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.Id })|
                            @Html.ActionLink("Assign", "RoleAssign", new { id = item.Id })|

                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
        @await Component.InvokeAsync("Pager", Model)
    </div>
</div>

FGW-Enterprise-Web.AddminApp/Views/User/Login.cshtml
@using FGW_Enterprise_Web.ViewModels.System.Users
@model LoginRequest
@{ 
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Page Title - SB Admin</title>
    <link href="/css/styles.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-5">
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header"><h3 class="text-center font-weight-light my-4">Login 1</h3></div>
                                <div class="card-body">
                                    <form asp-action="Login" asp-controller="User" method="post">
                                        <div class="form-group">
                                            <label class="small mb-1" >UserName</label>
                                            <input class="form-control py-4" asp-for="UserName" type="text" placeholder="Enter UserName" />
                                        </div>
                                        <div class="form-group">
                                            <label class="small mb-1">Password</label>
                                            <input class="form-control py-4" asp-for="Password" type="password" placeholder="Enter password" />
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox">
                                                <input class="custom-control-input" asp-for="RememberMe" type="checkbox" />
                                                <label class="custom-control-label">Remember password</label>
                                            </div>
                                        </div>
                                        <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                            <a class="small" href="/User/ForgotPassword">Forgot Password?</a>
                                            <button class="btn btn-primary" type="submit">Login</button>
                                        </div>
                                    </form>
                                </div>
                                <div class="card-footer text-center">
                                    <div class="small">Contact staff</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutAuthentication_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2020</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="/js/scripts.js"></script>
</body>
</html>

FGW-Enterprise-Web.AddminApp/Views/User/RoleAssign.cshtml
@model FGW_Enterprise_Web.ViewModels.System.Users.RoleAssignRequest

@{
    ViewData["Title"] = "Gán quyền";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <h1 class="mt-4">Gán quyền</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Gán quyền</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index" asp-controller="User">Về danh sách</a>
        </div>

        <div class="card-body">
            <form asp-action="RoleAssign">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                @for (var i = 0; i < Model.Roles.Count; i++)
                {
                    <div class="form-group">
                        <label>
                            @Model.Roles[i].Name
                            <input type="checkbox" asp-for="Roles[i].Selected" />
                            <input type="hidden" asp-for="Roles[i].Id" />
                            <input type="hidden" asp-for="Roles[i].Name" />
                        </label>
                    </div>
                }
                <div class="form-group">
                    <input type="submit" value="Lưu lại" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>